version: "3"
services:
  web:
    #image: git_limited
    image: go_react
    volumes:
      - ./:/go/src/git_limited_access
      - ./default.conf:/etc/nginx/conf.d/default.conf
    container_name: git_limited
    ports:
      - "80:80"
    tty: true
    privileged: true
    links:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodata/db:/data/db
      - ./mongodata/configdb:/data/configdb